plugins:
  - jekyll-relative-links
name: Workshop on Centrality Indicators in Road Network Analysis: from concept to implementation
title: Workshop on Centrality Indicators in Road Network Analysis: from concept to implementation
relative_links:
  enabled: true
  collections: true
include:
  - index.md
